### ISSUE TITLE
incorrect snapshot url

### ISSUE THREAD

**Issue by skenaja** [etherlinkcom/docs#148]
https://docs.etherlink.com/network/smart-rollup-nodes

> Download the latest snapshot from https://snapshots.eu.tzinit.org/etherlink-mainnet/, which is named eth-mainnet.snapshot:

The snapshot file seems to have been renamed - if you run the `wget` command as-is, you get a 404 error.

According to https://snapshots.eu.tzinit.org/etherlink-mainnet/ the file is https://snapshots.eu.tzinit.org/etherlink-mainnet/eth-mainnet.full (different filename referenced in a few places on the docs)

**Comment by timothymcmackin** [comment]
Thanks for pointing that out! I created a PR to fix it.
