### ISSUE TITLE
Deadlink for network information

### ISSUE THREAD

**Issue by phink** [etherlinkcom/docs#155]
Hello,

the link https://docs.etherlink.com/get-started/using-your-wallet/network-information referenced in https://docs.etherlink.com/get-started/using-your-wallet/ at 
> To connect your wallet manually, use the parameters in [Network information](https://docs.etherlink.com/get-started/using-your-wallet/network-information).

is dead.

I guess it should be the following https://docs.etherlink.com/get-started/network-information/.

**Comment by timothymcmackin** [comment]
This is just like https://github.com/etherlinkcom/docs/pull/149. The link path is correct but some people get routed to the wrong path. I wonder why this is happening.

**Comment by timothymcmackin** [comment]
It may come down to whether you've got a slash at the end of the URL in your browser or not. I will change the links to be all root-relative and that should fix it.

**Comment by phink** [comment]
Looks good. I am not able to reproduce a scenario in which the provided link is https://docs.etherlink.com/get-started/using-your-wallet/network-information. Thanks for your responsiveness!
