### ISSUE TITLE
Public RPC endpoint provided by Zeeve is no longer working

### ISSUE THREAD

**Issue by phink** [etherlinkcom/docs#94]
Hi,

I believe the link referencing the 'Etherlink Testnet - public RPC' endpoint provided by Zeeve is no longer working: https://etherlink-ghostnet-6lcp5r.zeeve.net/rpc, as found at https://docs.etherlink.com/tools/node-providers.

I have sent an email to Zeeve to know whether they are still running a public RPC endpoint. I will keep you updated with their response. 

In the meantime, we may want to remove the link.

**Comment by timothymcmackin** [comment]
Thanks for catching this! I removed the link but will leave this issue open as a reminder to find out whether Zeeve still provides a public RPC endpoint.

**Comment by phink** [comment]
Sure. Thanks !

**Comment by timothymcmackin** [comment]
@phink Any news here? Does Zeeve provide a public RPC endpoint?

**Comment by timothymcmackin** [comment]
They are not currently providing an RPC endpoint.
